title: Programming Course | Noor Academia
url: "https://nooracademia.in"
baseurl: ""

# Tell Jekyll where to find the synced Sass files from the Vault
sass:
  sass_dir: _sass
  style: compressed

# Root path for synced assets (icons, etc.)
vault_url: "/assets/vault"

# Standard Jekyll Plugins
plugins:
  - jekyll-seo-tag

# Ensure Jekyll includes all the folders we are syncing from the Private Vault
include:
  - _data
  - _layouts
  - _includes
  - _sass
  - assets
