name: Remote Handler
on:
  repository_dispatch:
    types: [trigger_from_main]
  workflow_dispatch:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    # ADD THIS BLOCK BELOW
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remote trigger received
        run: echo "Starting the Sync Private Repo workflow..."

      - name: Trigger Sync Private Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run "Sync Private Repo"
