name: Sync to Publish Repo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Publish
        env:
          TOKEN: ${{ secrets.PUBLISH_P_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Standardizing the remote URL format
          git remote add target https://x-access-token:${TOKEN}@github.com/noorvaultpublish/program-nooracademia-in-publish.git
          git push target main:main --force
          
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Use the token in the URL directly
          git remote add target https://x-access-token:${TOKEN}@github.com/noorvaultpublish/program-nooracademia-in-publish.git
          
          git push target main:main --force
