name: Sync to Publish Repo
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

     - name: Pull and Merge from Source
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          git remote add source https://x-access-token:${{ secrets.PUBLISH_P_TOKEN }}@github.com/nooracademia-owner/program-nooracademia.in.git
          
          git fetch source main
          git checkout main
          
          # Merge but don't commit yet
          git merge source/main --allow-unrelated-histories --no-commit --no-ff
          
          # This command forces the workflows folder to stay exactly as it is in YOUR repo
          git checkout HEAD .github/workflows/
          
          # Now commit the other code and push
          git commit -m "Sync code only (ignoring workflows)" || echo "No changes"
          git push origin main
