name: Copy assets from vault

on:
  workflow_dispatch:

  permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the public repo (program)
      - name: Checkout program repo
        uses: actions/checkout@v4

      # Checkout the private repo (vault)
      - name: Checkout vault repo
        uses: actions/checkout@v4
        with:
          repository: nooracademia-owner/vault-noor-academia-in
          token: ${{ secrets.PRIVATE_TOKEN }}
          path: vault

      # Copy assets
      - name: Copy assets folder
        run: |
          mkdir -p assets
          cp -r vault/assets/* assets/

      # Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets
          git commit -m "Copy assets from vault" || echo "No changes"
          git push
